[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
casper-types = { workspace = true }
casper-event-standard = { path = "../casper-event-standard" }
casper-contract = { workspace = true, optional = true, features = ["no-std-helpers"] }
casper-engine-test-support = { workspace = true, optional = true }
casper-execution-engine = { workspace = true, optional = true }

[features]
default = ["test-support", "contract-support"]
contract-support = [ "dep:casper-contract" ]
test-support = [ "dep:casper-engine-test-support", "dep:casper-execution-engine" ]

[[bin]]
name = "event_producer"
path = "bin/event_producer.rs"
required-features = ["contract-support"]

[[bin]]
name = "event_initializer"
path = "bin/event_initializer.rs"
required-features = ["contract-support"]

[[test]]
name = "vm_tests"
path = "tests/vm_tests.rs"
required-features = ["test-support"]